[project]
name = "lead_curator"
version = "0.1.0"
description = "lead_curator using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crawl4ai>=0.9.2",
    "crewai[litellm,tools]>=1.14.0,<1.14.7",
    "nest-asyncio>=1.6.0",
    "pydantic[email]>=2.11.10",
    "requests>=2.34.2",
]

[project.scripts]
lead_curator = "lead_curator.main:run"
run_crew = "lead_curator.main:run"
train = "lead_curator.main:train"
replay = "lead_curator.main:replay"
test = "lead_curator.main:test"
run_with_trigger = "lead_curator.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
